defaults:
  - _self_
  - augmentations: symmetric_weak.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simsiam-tinyimagenet"
method: "simsiam"
backbone:
  name: "resnet34"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  pred_hidden_dim: 4096
  temperature: 0.2
data:
  dataset: tinyimagenet #
  train_path: "../../datasets/tiny-imagenet-200/train"
  val_path: "../../datasets/tiny-imagenet-200/train"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.5
  classifier_lr: 0.1
  weight_decay: 1e-5
scheduler:
  name: "warmup_cosine"
  warmup_epochs: 50
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 1000
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
#strategy: "ddp"
precision: 16

cluster_eval:
  enabled: True
  freq: 20
  preds_k: 200
  targets_k: 200
process_bar:
  enabled: True
  refresh_rate: 100