defaults:
  - _self_
  - augmentations: symmetric_weak.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "mocov2plus-imagenetdogs"
method: "mocov2plus"
backbone:
  name: "resnet34"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  queue_size: 32768
  temperature: 0.2
momentum:
  base_tau: 0.99
  final_tau: 0.999
data:
  dataset: imagenetdogs
  train_path: "../../datasets/imagenet10"
  val_path: "../../datasets/imagenet10"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.5
  classifier_lr: 0.1
  weight_decay: 1e-4
scheduler:
  name: "warmup_cosine"
  warmup_epochs: 50
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 1000
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
#strategy: "ddp"
precision: 16


cluster_eval:
  enabled: True
  freq: 20
  preds_k: 15
  targets_k: 15
process_bar:
  enabled: True
  refresh_rate: 30